### ISSUE TITLE
Why so slow?

### ISSUE THREAD

**Issue by strider72** [fny/calibre-Installer#4]
If I manually download Calibre from the download link on the site, it takes about a minute.  If I download this from the Installer, it takes over ten minutes.  I've tried it multiple times to make sure it wasn't a one-time glitch.

**Comment by fny** [comment]
Hmm... will have to look into this.

At first glance, it looks like they've changed the URL from from `http://status.calibre-ebook.com/dist/osx32` to `http://code.calibre-ebook.com/dist/osx32`. See if you notice a difference downloading those URLs from the browser.  Not sure it'll make a difference though since the servers IP is the same for both addresses (166.78.100.224).

**Comment by strider72** [comment]
As a test I actually changed it to the same link at the manual download.  Still much slower.

**Comment by fny** [comment]
On the new URL (http://calibre-ebook.com/dist/osx), download times seem no different for me (2-3 min). Hopefully that was just a fluke!
